name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install BLAS and LAPACK
        run: sudo apt-get install -y libopenblas-dev libatlas-base-dev liblapacke-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: bundle exec rake
